# Generated by Django 4.1.7 on 2023-03-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='word_char_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cns_code', models.CharField(max_length=7)),
                ('unicode_code', models.CharField(max_length=5)),
                ('big5_code', models.CharField(max_length=5)),
            ],
        ),
    ]
