# Generated by Django 4.1.7 on 2023-03-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word_char_code',
            name='big5_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='word_char_code',
            name='unicode_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
