# Generated by Django 4.1.7 on 2023-03-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_crud', '0003_alter_word_char_code_big5_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='word_char_code',
            name='chinese_char',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
