# Generated by Django 4.1.7 on 2023-03-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_crud', '0004_word_char_code_chinese_char'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='word_char_code',
            new_name='WordModels',
        ),
    ]
